[project]
name = "todo"
version = "0.1.0"
description = "Toy TODO app for BE interviews"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.14",
    "sqlalchemy>=2.0.41",
]
